# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-24 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProTwo', '0002_auto_20171221_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
